### PR TITLE
Improved readability

### PR DESCRIPTION
**Pull request by AtHeartEngineer**
Changed the background color of the floating box in the apply section, to a darker color so it is more readable.

### CODE REVIEW

**Comment by AtHeartEngineer** [comment]
DM Me on discord if you want to discuss anything

**Comment by luxumbra** [comment]
why clos it ser?

**Comment by AtHeartEngineer** [comment]
DM Me on discord if you want to discuss anything

> 

Hey, someone in the discord told me to fork instead. I can re-open this if you want.

**Comment by luxumbra** [comment]
LGTM @AtHeartEngineer if you want to re-open.

**Pull request closed without merging**
